version: "3"

services:
  screenshot-server:
    build: screenshot-server
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=5000
      - SERVER_NAME=localhost
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/tmp
      - SECRET=TEST
