version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always

  screenshot-server:
    environment:
      VIRTUAL_HOST: XXXXXXXX
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: XXXXXXXX
      LETSENCRYPT_EMAIL: XXXXXXXX
      SERVER_NAME: XXXXXXXX
      FLASK_ENV: production
      UPLOAD_FOLDER: /mnt/uploads
      SECRET: XXXXXXXX
    volumes:
      - uploads:/mnt/uploads
    restart: always

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  uploads:

networks:
  default:
    external:
      name: nginx-proxy
