version: "3"

services:
  screenshot-server:
    environment:
      VIRTUAL_HOST: XXXXXXXX
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: XXXXXXXX
      LETSENCRYPT_EMAIL: XXXXXXXX
      SERVER_NAME: XXXXXXXX
      FLASK_ENV: production
      UPLOAD_FOLDER: /mnt/uploads
      SECRET: XXXXXXXX
    volumes:
      - uploads:/mnt/uploads
    restart: always
    networks:
      - shared

networks:
  shared:
    external:
      name: nginx-proxy

volumes:
  uploads:
